name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/peerhire-api .
          docker push ${{ secrets.DOCKER_USERNAME }}/peerhire-api

      - name: 🚀 Deploy PeerHire API to EC2 Instance
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
             echo "🔄 Pulling latest Docker image from Docker Hub..."
             docker pull ${{ secrets.DOCKER_USERNAME }}/peerhire-api:latest
             echo "🛑 Stopping old PeerHire container if running..."
             docker stop peerhire-api || true
             docker rm peerhire-api || true
             echo "🚀 Starting new PeerHire container on port 3000..."
             docker run -d \
                 --name peerhire-api \
                 -p 3000:3000 \
                 ${{ secrets.DOCKER_USERNAME }}/peerhire-api:latest

             echo "✅ Deployment complete!"

